service: auth

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: staging

  memorySize: 512

  environment:
      TABLE_NAME: ServerlessAuthTable-${self:custom.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
      Resource:
        - "Fn::GetAtt": [ServerlessAuthTable, Arn]
  httpApi:
    cors:
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
      allowCredentials: true
    authorizers:
      mainJwtAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: auth.smartprograms.co
        audience:
          - chat.smartprograms.co

functions:
  OAuthClients:
    name: OAuth-List-Clients-${self:custom.stage}
    handler:
      - ${self:custom.prefix.${self:custom.stage}}/oauth/clients/index.handler
    package:
      include:
        - ${self:custom.prefix.${self:custom.stage}}/oauth/clients/index.ts
    events:
      - httpApi:
          method: GET
          path: /oauth/clients
  OAuthLogin:
    name: OAuth-Client-Login-${self:custom.stage}
    handler:
      - ${self:custom.prefix.${self:custom.stage}}/oauth/login/index.handler
    package:
      include:
        - ${self:custom.prefix.${self:custom.stage}}/oauth/login/index.ts
    events:
      - httpApi:
          method: POST
          path: /oauth/login/{client}
  OAuthLoginRedirect:
    name: OAuth-Login-Redirect-${self:custom.stage}
    handler:
      - ${self:custom.prefix.${self:custom.stage}}/oauth/login/redirect.handler
    package:
      include:
        - ${self:custom.prefix.${self:custom.stage}}/oauth/login/redirect.ts
    events:
      - httpApi:
          method: GET
          path: /oauth/login/{client}/redirect

resources:
  Resources:
    ServerlessAuthTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  # - serverless-domain-manager
  # - serverless-prune-plugin

package:
  individually: true
  exclude:
    - ./**

custom:
  stage: ${opt:stage, self:provider.stage}
  dynamodb:
    stages:
      - staging
    start:
      port: 8000
      inMemory: true
      migrate: true
  prefix:
    prod: 'build'
    staging: 'dev-build'
  # domains:
  #   prod: 'auth.gchserverless.com'
  #   staging: 'staging-auth.gchserverless.com'
  # customDomain:
  #   domainName: ${self:custom.domains.${self:custom.stage}}
  #   basePath: 'users'
  #   stage: ${self:custom.stage}
  #   createRoute53Record: true
  # prune:
  #   automatic: true
  #   number: 2
